#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# WordPress Docker - Interactive Setup Wizard
# =============================================================================

# --- Colors & formatting ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# --- Helper functions ---

print_header() {
    echo ""
    echo -e "${BOLD}"
    echo "  ╔════════════════════════════════════════════╗"
    echo "  ║     WordPress Docker - Setup Wizard        ║"
    echo "  ╚════════════════════════════════════════════╝"
    echo -e "${RESET}"
}

ok()    { echo -e "  ${GREEN}✓${RESET} $1"; }
fail()  { echo -e "  ${RED}✗${RESET} $1"; }
info()  { echo -e "  ${BLUE}→${RESET} $1"; }
warn()  { echo -e "  ${YELLOW}!${RESET} $1"; }
step()  { echo -e "\n${BOLD}$1${RESET}"; }

# Prompt with default value. Usage: result=$(ask "Port" "8080")
ask() {
    local prompt="$1"
    local default="$2"
    local value
    echo -ne "  ${BOLD}?${RESET} ${prompt} ${DIM}[${default}]${RESET}: " >&2
    read -r value
    echo "${value:-$default}"
}

# Prompt for sensitive value with hidden default. Usage: result=$(ask_secret "Password" "auto")
ask_secret() {
    local prompt="$1"
    local default="$2"
    local display="auto-generated"
    local value
    echo -ne "  ${BOLD}?${RESET} ${prompt} ${DIM}[${display}]${RESET}: " >&2
    read -r value
    echo "${value:-$default}"
}

# Yes/No prompt. Usage: if confirm "Continue?" "y"; then ...
confirm() {
    local prompt="$1"
    local default="${2:-y}"
    local hint="Y/n"
    [[ "$default" == "n" ]] && hint="y/N"
    local value
    echo -ne "  ${BOLD}?${RESET} ${prompt} ${DIM}[${hint}]${RESET}: " >&2
    read -r value
    value="${value:-$default}"
    [[ "${value,,}" == "y" || "${value,,}" == "yes" ]]
}

generate_password() {
    openssl rand -base64 18 2>/dev/null || LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
}

# Find first available port starting from a given number
find_free_port() {
    local port="${1:-8080}"
    while lsof -i :"$port" &>/dev/null 2>&1; do
        ((port++))
    done
    echo "$port"
}

# Derive project name from directory name (lowercase, alphanumeric + hyphens)
default_project_name() {
    basename "$PWD" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//'
}

# --- Prerequisites check ---

check_prerequisites() {
    step "Checking prerequisites..."

    local has_error=false

    if command -v docker &>/dev/null; then
        ok "Docker found"
    else
        fail "Docker not found. Please install Docker first."
        has_error=true
    fi

    if docker compose version &>/dev/null; then
        ok "Docker Compose found"
    elif command -v docker-compose &>/dev/null; then
        ok "Docker Compose (legacy) found"
    else
        fail "Docker Compose not found. Please install Docker Compose."
        has_error=true
    fi

    if docker info &>/dev/null 2>&1; then
        ok "Docker daemon running"
    else
        fail "Docker daemon not running. Please start Docker."
        has_error=true
    fi

    # rsync is optional but recommended for server pull
    if command -v rsync &>/dev/null; then
        ok "rsync found"
    else
        warn "rsync not found — server file pull will use scp (slower, no incremental sync)"
        info "Install rsync for better performance: ${BOLD}brew install rsync${RESET}"
    fi

    if [[ "$has_error" == true ]]; then
        echo ""
        fail "Prerequisites not met. Please fix the issues above and try again."
        exit 1
    fi
}

# --- .env handling ---

check_existing_env() {
    if [[ -f .env ]]; then
        echo ""
        warn "An existing .env file was found."
        if ! confirm "Overwrite it?" "n"; then
            echo ""
            info "Setup cancelled. Your existing .env was not modified."
            exit 0
        fi
        echo ""
    fi
}

create_env() {
    local port="$1"
    local php_version="$2"
    local root_pass="$3"
    local db_name="$4"
    local db_user="$5"
    local db_pass="$6"
    local project_name="$7"

    cat > .env <<EOF
# WordPress Docker Environment Configuration
# Generated by setup wizard on $(date +%Y-%m-%d)

# Project name (used for container, volume, and network names)
COMPOSE_PROJECT_NAME=${project_name}

# Port for WordPress (host:container 80)
WP_PORT=${port}

# PHP version (available: 8.0, 8.1, 8.2, 8.3, 8.4)
# After changing, rebuild: make build
PHP_VERSION=${php_version}

# MySQL/MariaDB Configuration
MYSQL_ROOT_PASSWORD=${root_pass}
MYSQL_DATABASE=${db_name}
MYSQL_USER=${db_user}
MYSQL_PASSWORD=${db_pass}
EOF

    ok "Created .env"
    info "Containers: ${BOLD}${project_name}-wordpress-1${RESET}, ${BOLD}${project_name}-db-1${RESET}"
}

# --- Common config prompts ---

# Parse DB credentials from remote wp-config.php
# Sets REMOTE_DB_NAME, REMOTE_DB_USER, REMOTE_DB_PASS globals
parse_remote_wp_config() {
    local server="$1" wp_path="$2"
    local wp_config
    wp_config=$(ssh "$server" "cat '$wp_path/wp-config.php'" 2>/dev/null) || return 1

    # Extract values using awk (portable across macOS and Linux)
    extract_wp_define() {
        echo "$1" | awk -F"'" "/define[[:space:]]*\\([[:space:]]*'$2'/{print \$4}" | head -1
    }
    REMOTE_DB_NAME=$(extract_wp_define "$wp_config" "DB_NAME")
    REMOTE_DB_USER=$(extract_wp_define "$wp_config" "DB_USER")
    REMOTE_DB_PASS=$(extract_wp_define "$wp_config" "DB_PASSWORD")

    if [[ -n "$REMOTE_DB_NAME" && -n "$REMOTE_DB_USER" ]]; then
        return 0
    fi
    return 1
}

# Mask password for display (show first 2 chars + asterisks)
mask_password() {
    local pass="$1"
    if [[ ${#pass} -le 2 ]]; then
        echo "***"
    else
        echo "${pass:0:2}$(printf '%*s' $((${#pass}-2)) '' | tr ' ' '*')"
    fi
}

ask_common_config() {
    step "Configuration"

    local default_name
    default_name=$(default_project_name)
    PROJECT_NAME=$(ask "Project name (used for container names)" "$default_name")

    local free_port
    free_port=$(find_free_port 8080)
    if [[ "$free_port" != "8080" ]]; then
        info "Port 8080 is in use, suggesting ${free_port}"
    fi
    WP_PORT=$(ask "WordPress port" "$free_port")

    echo -ne "  ${BOLD}?${RESET} PHP version (8.0/8.1/8.2/8.3/8.4) ${DIM}[8.2]${RESET}: " >&2
    read -r PHP_VER
    PHP_VER="${PHP_VER:-8.2}"

    local auto_root_pass
    auto_root_pass=$(generate_password)
    MYSQL_ROOT_PASS=$(ask_secret "MySQL root password" "$auto_root_pass")

    # Use remote defaults if available (set by parse_remote_wp_config)
    local db_default="${REMOTE_DB_NAME:-wordpress}"
    local user_default="${REMOTE_DB_USER:-wp}"
    local pass_default="${REMOTE_DB_PASS:-}"

    MYSQL_DB=$(ask "MySQL database name" "$db_default")
    MYSQL_USER_NAME=$(ask "MySQL user" "$user_default")

    if [[ -n "$pass_default" ]]; then
        MYSQL_PASS=$(ask_secret "MySQL password" "$pass_default")
    else
        local auto_pass
        auto_pass=$(generate_password)
        MYSQL_PASS=$(ask_secret "MySQL password" "$auto_pass")
    fi
}

# --- Wait for containers to be healthy ---

wait_for_db() {
    echo -ne "  ${BLUE}⏳${RESET} Waiting for database"
    local retries=30
    while [[ $retries -gt 0 ]]; do
        if docker compose exec -T db mysqladmin ping -h localhost -u root -p"${MYSQL_ROOT_PASS}" &>/dev/null 2>&1; then
            echo ""
            ok "Database is ready"
            return 0
        fi
        echo -n "."
        sleep 2
        ((retries--))
    done
    echo ""
    fail "Database did not become ready in time. Check: make logs"
    exit 1
}

# --- Start containers ---

start_containers() {
    info "Building and starting containers (this may take a minute on first run)..."
    if ! docker compose up -d --build 2>&1; then
        fail "Failed to start containers. Check the output above for details."
        echo -e "  ${DIM}Common causes:${RESET}"
        echo -e "  ${DIM}  - Port ${WP_PORT} already in use (try a different port)${RESET}"
        echo -e "  ${DIM}  - Docker daemon not running${RESET}"
        echo -e "  ${DIM}  - Insufficient disk space${RESET}"
        exit 1
    fi
    ok "Containers started"
    wait_for_db
}

# --- Path 1: Fresh WordPress ---

setup_fresh() {
    create_env "$WP_PORT" "$PHP_VER" "$MYSQL_ROOT_PASS" "$MYSQL_DB" "$MYSQL_USER_NAME" "$MYSQL_PASS" "$PROJECT_NAME"

    step "Starting WordPress"
    start_containers

    echo ""
    echo -e "  ${GREEN}${BOLD}Setup complete!${RESET}"
    echo ""
    info "WordPress is running at ${BOLD}http://localhost:${WP_PORT}${RESET}"
    info "Complete the WordPress installation in your browser."
    echo ""
    echo -e "  ${DIM}Useful commands:${RESET}"
    echo -e "  ${DIM}  make logs             Follow container logs${RESET}"
    echo -e "  ${DIM}  make down             Stop containers${RESET}"
    echo -e "  ${DIM}  make wp -- <cmd>      Run WP-CLI commands${RESET}"
    echo ""
}

# --- Path 2: Import existing site ---

wait_for_dump() {
    if [[ -f data/dump.sql.gz ]]; then
        ok "Found data/dump.sql.gz"
        return 0
    elif [[ -f data/dump.sql ]]; then
        ok "Found data/dump.sql"
        return 0
    fi

    echo ""
    warn "No dump file found in data/"
    echo ""
    echo -e "  Place your database dump in the ${BOLD}data/${RESET} directory:"
    echo -e "    - data/dump.sql      ${DIM}(uncompressed)${RESET}"
    echo -e "    - data/dump.sql.gz   ${DIM}(gzip compressed)${RESET}"
    echo ""
    echo -ne "  Press ${BOLD}Enter${RESET} when ready, or ${BOLD}Ctrl+C${RESET} to abort... "
    read -r

    if [[ -f data/dump.sql.gz ]]; then
        ok "Found data/dump.sql.gz"
    elif [[ -f data/dump.sql ]]; then
        ok "Found data/dump.sql"
    else
        fail "Still no dump file found. Aborting."
        exit 1
    fi
}

check_wp_content() {
    if ! confirm "Do you have wp-content to import?" "y"; then
        return
    fi

    if [[ -d data/wp-content ]]; then
        local plugins=0 themes=0
        [[ -d data/wp-content/plugins ]] && plugins=$(find data/wp-content/plugins -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
        [[ -d data/wp-content/themes ]] && themes=$(find data/wp-content/themes -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
        ok "Found data/wp-content/ (${plugins} plugins, ${themes} themes)"
        return
    fi

    echo ""
    echo -e "  Place your wp-content directory at ${BOLD}data/wp-content/${RESET}"
    echo ""
    echo -ne "  Press ${BOLD}Enter${RESET} when ready... "
    read -r

    if [[ -d data/wp-content ]]; then
        local plugins=0 themes=0
        [[ -d data/wp-content/plugins ]] && plugins=$(find data/wp-content/plugins -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
        [[ -d data/wp-content/themes ]] && themes=$(find data/wp-content/themes -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
        ok "Found data/wp-content/ (${plugins} plugins, ${themes} themes)"
    else
        warn "data/wp-content/ not found. Continuing without it."
    fi
}

setup_import() {
    step "Database dump"
    mkdir -p data
    wait_for_dump

    step "WordPress content"
    check_wp_content

    create_env "$WP_PORT" "$PHP_VER" "$MYSQL_ROOT_PASS" "$MYSQL_DB" "$MYSQL_USER_NAME" "$MYSQL_PASS" "$PROJECT_NAME"

    step "Starting WordPress"
    start_containers

    step "Importing database"
    info "Importing database dump (this may take a while for large databases)..."
    if ! make import-db; then
        fail "Database import failed. Check that the dump file is valid."
        echo -e "  ${DIM}Try: gunzip -t data/dump.sql.gz  (to verify the file)${RESET}"
        exit 1
    fi
    ok "Database imported"

    step "URL replacement"
    local old_url
    echo -ne "  ${BOLD}?${RESET} Production site URL (e.g. https://example.com): " >&2
    read -r old_url

    if [[ -n "$old_url" ]]; then
        info "Replacing ${old_url} → http://localhost:${WP_PORT} in database..."
        if ! make replace-urls OLD="$old_url" NEW="http://localhost:${WP_PORT}"; then
            fail "URL replacement failed. You can retry later with:"
            echo -e "    ${DIM}make replace-urls OLD=${old_url}${RESET}"
        else
            ok "URLs replaced"
        fi
    else
        warn "Skipped URL replacement. You can do it later with:"
        echo -e "    ${DIM}make replace-urls OLD=https://your-site.com${RESET}"
    fi

    echo ""
    echo -e "  ${GREEN}${BOLD}Setup complete!${RESET}"
    echo ""
    info "WordPress is running at ${BOLD}http://localhost:${WP_PORT}${RESET}"
    echo ""
    echo -e "  ${DIM}Useful commands:${RESET}"
    echo -e "  ${DIM}  make logs             Follow container logs${RESET}"
    echo -e "  ${DIM}  make down             Stop containers${RESET}"
    echo -e "  ${DIM}  make wp -- user list  List WordPress users${RESET}"
    echo -e "  ${DIM}  make wp -- user update admin --user_pass=newpass${RESET}"
    echo ""
}

# --- Path 3: Pull from server ---

setup_pull() {
    step "Server connection"
    local server wp_path pull_mode

    echo -ne "  ${BOLD}?${RESET} SSH connection (user@host): " >&2
    read -r server
    if [[ -z "$server" ]]; then
        fail "SSH connection is required."
        exit 1
    fi

    # Test SSH connection before proceeding
    info "Testing SSH connection to ${BOLD}${server}${RESET}..."
    if ! ssh -o ConnectTimeout=10 -o BatchMode=yes "$server" "echo ok" &>/dev/null; then
        fail "Cannot connect to ${server} via SSH."
        echo -e "  ${DIM}Check that:${RESET}"
        echo -e "  ${DIM}  - The host is reachable${RESET}"
        echo -e "  ${DIM}  - Your SSH key is configured (ssh-add -l)${RESET}"
        echo -e "  ${DIM}  - The username is correct${RESET}"
        exit 1
    fi
    ok "SSH connection successful"

    # Try to auto-detect WordPress installations on the server
    step "WordPress path"
    info "Searching for WordPress installations on server..."

    local detected_paths=()
    local search_result
    # Check common locations first (fast), then fall back to find (slower)
    search_result=$(ssh "$server" "
        found=()
        # Common WordPress locations
        for dir in \
            /var/www/html \
            /var/www/*/html \
            /var/www/*/public_html \
            /var/www/*/public \
            /var/www/*/htdocs \
            /home/*/public_html \
            /home/*/www \
            /home/*/htdocs \
            /srv/www/* \
            /var/www/* \
        ; do
            if [ -f \"\$dir/wp-config.php\" ] 2>/dev/null; then
                echo \"\$dir\"
            fi
        done
        # If nothing found in common dirs, try find (limit depth & time)
        if [ \${#found[@]} -eq 0 ]; then
            timeout 10 find /var/www /home /srv/www -maxdepth 4 -name wp-config.php -type f 2>/dev/null | while read -r f; do
                dirname \"\$f\"
            done
        fi
    " 2>/dev/null || true)

    if [[ -n "$search_result" ]]; then
        # Read results into array
        while IFS= read -r line; do
            [[ -n "$line" ]] && detected_paths+=("$line")
        done <<< "$search_result"
    fi

    if [[ ${#detected_paths[@]} -eq 1 ]]; then
        ok "Found WordPress installation: ${BOLD}${detected_paths[0]}${RESET}"
        wp_path=$(ask "WordPress path on server" "${detected_paths[0]}")
    elif [[ ${#detected_paths[@]} -gt 1 ]]; then
        ok "Found ${#detected_paths[@]} WordPress installations:"
        local i=1
        for p in "${detected_paths[@]}"; do
            echo -e "    ${BOLD}${i})${RESET} ${p}"
            ((i++))
        done
        echo ""
        echo -ne "  ${BOLD}?${RESET} Choose installation ${DIM}[1]${RESET} or enter path manually: " >&2
        read -r wp_choice
        wp_choice="${wp_choice:-1}"
        if [[ "$wp_choice" =~ ^[0-9]+$ ]] && (( wp_choice >= 1 && wp_choice <= ${#detected_paths[@]} )); then
            wp_path="${detected_paths[$((wp_choice-1))]}"
        else
            # User typed a custom path
            wp_path="$wp_choice"
        fi
    else
        warn "Could not auto-detect WordPress path"
        echo -ne "  ${BOLD}?${RESET} WordPress path on server (e.g. /var/www/html): " >&2
        read -r wp_path
    fi

    if [[ -z "$wp_path" ]]; then
        fail "WordPress path is required."
        exit 1
    fi

    # Verify the path exists and contains WordPress
    info "Verifying WordPress at ${BOLD}${wp_path}${RESET}..."
    if ! ssh "$server" "test -d '$wp_path'" 2>/dev/null; then
        fail "Directory ${wp_path} does not exist on ${server}."
        exit 1
    fi
    if ! ssh "$server" "test -f '$wp_path/wp-config.php'" 2>/dev/null; then
        warn "wp-config.php not found in ${wp_path} — this may not be a WordPress root"
        if ! confirm "Continue anyway?" "n"; then
            exit 1
        fi
    else
        ok "WordPress confirmed at ${wp_path}"
    fi

    # Try to read DB credentials from remote wp-config.php
    step "Database credentials"
    REMOTE_DB_NAME="" REMOTE_DB_USER="" REMOTE_DB_PASS=""

    if confirm "Read DB credentials from server's wp-config.php?" "y"; then
        info "Reading wp-config.php from server..."
        if parse_remote_wp_config "$server" "$wp_path"; then
            ok "Credentials detected from wp-config.php:"
            echo -e "    ${DIM}DB_NAME:     ${RESET}${REMOTE_DB_NAME}"
            echo -e "    ${DIM}DB_USER:     ${RESET}${REMOTE_DB_USER}"
            echo -e "    ${DIM}DB_PASSWORD: ${RESET}$(mask_password "$REMOTE_DB_PASS")"
            echo ""
            info "These will be used as defaults for local configuration"
        else
            warn "Could not read credentials from wp-config.php"
            info "You will enter database credentials manually"
        fi
    else
        info "You will enter database credentials manually"
    fi

    # Now ask for local configuration (with remote defaults if detected)
    ask_common_config

    echo ""
    echo -e "  ${BOLD}?${RESET} What to pull?"
    echo -e "    ${BOLD}1)${RESET} Everything (files + database)"
    echo -e "    ${BOLD}2)${RESET} Files only (wp-content)"
    echo -e "    ${BOLD}3)${RESET} Database only"
    echo -ne "  Choice ${DIM}[1]${RESET}: "
    read -r pull_mode
    pull_mode="${pull_mode:-1}"

    create_env "$WP_PORT" "$PHP_VER" "$MYSQL_ROOT_PASS" "$MYSQL_DB" "$MYSQL_USER_NAME" "$MYSQL_PASS" "$PROJECT_NAME"

    step "Starting WordPress"
    start_containers

    step "Pulling from server"
    case "$pull_mode" in
        1)
            info "Pulling files from ${server}:${wp_path}/wp-content/..."
            if ! make pull-files SERVER="$server" WP_PATH="$wp_path"; then
                fail "Failed to pull files from server. Check SSH access and path permissions."
                exit 1
            fi
            ok "Files pulled successfully"

            info "Exporting database from ${server}..."
            if ! make pull-db SERVER="$server" WP_PATH="$wp_path"; then
                fail "Failed to export database. Check that WP-CLI is installed on the server."
                echo -e "  ${DIM}Alternative: export manually with mysqldump and place dump.sql in data/${RESET}"
                exit 1
            fi
            ok "Database exported successfully"

            info "Importing database into local container..."
            make import-db
            ok "Database imported"
            ;;
        2)
            info "Pulling files from ${server}:${wp_path}/wp-content/..."
            if ! make pull-files SERVER="$server" WP_PATH="$wp_path"; then
                fail "Failed to pull files from server. Check SSH access and path permissions."
                exit 1
            fi
            ok "Files pulled successfully"
            ;;
        3)
            info "Exporting database from ${server}..."
            if ! make pull-db SERVER="$server" WP_PATH="$wp_path"; then
                fail "Failed to export database. Check that WP-CLI is installed on the server."
                echo -e "  ${DIM}Alternative: export manually with mysqldump and place dump.sql in data/${RESET}"
                exit 1
            fi
            ok "Database exported successfully"

            info "Importing database into local container..."
            make import-db
            ok "Database imported"
            ;;
    esac

    # URL replacement (only if database was pulled)
    if [[ "$pull_mode" == "1" || "$pull_mode" == "3" ]]; then
        step "URL replacement"

        # Try auto-detecting the production URL
        info "Trying to auto-detect production URL..."
        local detected_url=""
        detected_url=$(ssh "$server" "cd $wp_path && wp option get siteurl 2>/dev/null" 2>/dev/null || true)

        local old_url
        if [[ -n "$detected_url" ]]; then
            ok "Detected: ${detected_url}"
            old_url=$(ask "Production site URL" "$detected_url")
        else
            warn "Could not auto-detect URL (WP-CLI may not be available)"
            echo -ne "  ${BOLD}?${RESET} Production site URL (e.g. https://example.com): " >&2
            read -r old_url
        fi

        if [[ -n "$old_url" ]]; then
            info "Replacing ${old_url} → http://localhost:${WP_PORT}..."
            make replace-urls OLD="$old_url" NEW="http://localhost:${WP_PORT}"
            ok "URLs replaced"
        else
            warn "Skipped URL replacement. Run later:"
            echo -e "    ${DIM}make replace-urls OLD=https://your-site.com${RESET}"
        fi
    fi

    echo ""
    echo -e "  ${GREEN}${BOLD}Setup complete!${RESET}"
    echo ""
    info "WordPress is running at ${BOLD}http://localhost:${WP_PORT}${RESET}"
    echo ""
    echo -e "  ${DIM}Useful commands:${RESET}"
    echo -e "  ${DIM}  make logs             Follow container logs${RESET}"
    echo -e "  ${DIM}  make down             Stop containers${RESET}"
    echo -e "  ${DIM}  make wp -- user list  List WordPress users${RESET}"
    echo -e "  ${DIM}  make wp -- user update admin --user_pass=newpass${RESET}"
    echo ""
}

# =============================================================================
# Main
# =============================================================================

print_header
check_prerequisites
check_existing_env

step "What would you like to do?"
echo -e "  ${BOLD}1)${RESET} Fresh WordPress installation"
echo -e "  ${BOLD}2)${RESET} Import existing site (from database dump)"
echo -e "  ${BOLD}3)${RESET} Pull from remote server (via SSH)"
echo ""
echo -ne "  Choice ${DIM}[1]${RESET}: "
read -r choice
choice="${choice:-1}"

case "$choice" in
    1) ask_common_config; setup_fresh ;;
    2) ask_common_config; setup_import ;;
    3) setup_pull ;;  # calls ask_common_config internally after SSH + wp-config parsing
    *)
        fail "Invalid choice: $choice"
        exit 1
        ;;
esac
